import { BLANK_TEMPLATE_ID, HOST_AGENT_ID, HOST_TEMPLATE_ID, type AgentTemplate } from './agent.ts'

/**
 * 新建 Agent 时的职业模板。每条都是内置模块的投影，
 * 雇佣快捷方式除外 —— 那是给用户看的一次雇出，不是可匹配的身体。
 */
export const BUILTIN_TEMPLATES: readonly AgentTemplate[] = [
  {
    id: BLANK_TEMPLATE_ID,
    role: '直接创建',
    description: '从空白开始，自由定义成员的扩展能力',
    persona: '通用助手。用对话把事情说清楚；收件箱里不 @ 的话仍会拆成待办。',
    mark: '空',
    hue: 4,
    agentKind: 'conversational',
    singleton: false,
    moduleIds: [],
    defaultAgentId: '',
    workspaceName: '',
    group: '直接创建',
    suggestedCapabilities: ['kernel', 'workspace'],
    toolPacks: ['kernel', 'workspace'],
  },
  {
    id: HOST_TEMPLATE_ID,
    role: '主理人',
    description: '默认出现在每个项目里：读改工作区、跑命令、查网页和 GitHub，先出计划再动手。',
    persona:
      '项目默认主成员。先看工作区再动手；改代码先对齐、红绿测试、最小补丁，改完对照验收和两轴审查。职业专项请 @ 对应成员。',
    mark: '主',
    hue: 4,
    agentKind: 'conversational',
    singleton: true,
    moduleIds: [],
    defaultAgentId: HOST_AGENT_ID,
    workspaceName: '工作台',
    group: '核心',
    suggestedCapabilities: ['kernel', 'workspace', 'mcp-github', 'mcp-browser'],
    toolPacks: ['kernel', 'workspace', 'mcp-github', 'mcp-browser'],
    planMode: true,
    inCatalog: false,
  },
  {
    id: 'engineer',
    role: '工程成员',
    description: '可另雇的工程同事。读改工作区、跑命令、查网页和 GitHub；每个项目默认已有主理人。',
    persona: '编程与调研助手。先看工作区再动手；改文件前能说明要动哪几处；做完对照验收自检。',
    mark: '程',
    hue: 4,
    agentKind: 'conversational',
    singleton: false,
    moduleIds: [],
    defaultAgentId: '',
    workspaceName: '工程',
    group: '直接创建',
    suggestedCapabilities: ['kernel', 'workspace', 'mcp-github', 'mcp-browser'],
    toolPacks: ['kernel', 'workspace', 'mcp-github', 'mcp-browser'],
    planMode: true,
  },
  {
    id: 'monitor',
    role: '项目监控官',
    description: '项目健康度、站点流量、全球性能、页面归因与后台用户统计，刷新时生成明日待办。',
    persona: '盯着目录里各站点的态势与全球 Web Vitals，刷新后把明日待办写进收件箱。',
    mark: '监',
    hue: 3,
    agentKind: 'dashboard',
    singleton: true,
    moduleIds: ['monitor'],
    viewId: 'monitor',
    defaultAgentId: 'monitor',
    workspaceName: '项目监控',
    group: '项目',
    suggestedCapabilities: ['todos:write'],
  },
  {
    id: 'micro',
    role: '选品策略师',
    description: '每天从 Reddit / Ask HN 捞真实痛点帖，按痛感 × 热度 × 贴合度聚类成产品 idea。',
    persona: '从英语用户的求助帖里捞愿意掏钱的信号，聚成可动手的产品 idea。',
    mark: '选',
    hue: 5,
    agentKind: 'dashboard',
    singleton: false,
    moduleIds: ['micro'],
    viewId: 'micro',
    defaultAgentId: 'micro-sourcing',
    workspaceName: '选品',
    group: '项目',
    suggestedCapabilities: ['todos:write', 'notify'],
  },
  {
    id: 'growth',
    role: '增长黑客',
    description: '把增长拆成可判定的实验、可复利的环和该扩/该停的渠道。流量看监控官，文案看弹药手，账本看财务顾问。',
    persona: '用实验、增长环和渠道表推进获客到留存。不写文案，不刷新流量，不碰账本。',
    mark: '增',
    hue: 8,
    agentKind: 'dashboard',
    singleton: true,
    moduleIds: ['growth'],
    viewId: 'growth',
    defaultAgentId: 'growth',
    workspaceName: '增长台',
    group: '项目',
    suggestedCapabilities: ['todos:write'],
  },
  {
    id: 'payments',
    role: '财务顾问',
    description: 'Creem 同步，加上分账、知识星球、微信扫码和海外社媒手录：营收、订阅、客户、结算与支出。',
    persona: '看营收、订阅和支出，心跳同步后把该跟进的收款事项推进待办。',
    mark: '收',
    hue: 1,
    agentKind: 'dashboard',
    singleton: true,
    moduleIds: ['payments'],
    viewId: 'payments',
    defaultAgentId: 'payments',
    workspaceName: '收款',
    group: '财务',
    suggestedCapabilities: ['secrets', 'todos:write', 'notify'],
  },
  {
    id: 'creator',
    role: '自媒体运营达人',
    description: '一次雇出自媒体账号和社媒弹药手。X 推送挂在弹药手上，不另开左栏身份。',
    persona: '把账号台和弹药手一次雇齐，中栏仍对着其中一个职业说话。',
    mark: '媒',
    hue: 2,
    agentKind: 'dashboard',
    singleton: false,
    moduleIds: ['accounts', 'social-ammo', 'x-push'],
    viewId: 'accounts',
    defaultAgentId: '',
    workspaceName: '自媒体',
    group: '内容',
    suggestedCapabilities: ['accounts', 'social-ammo', 'x-push'],
    hireTemplateIds: ['accounts', 'social-ammo'],
  },
  {
    id: 'wxdraft',
    role: '公众号编辑',
    description: '把 Markdown 主文档转成微信公众号草稿：取 token、转 HTML、上传封面、写入草稿箱。',
    persona: '把一篇 Markdown 收成公众号草稿。正文只做红线词、错别字和未格式化标记清理，不改表意。封面用手工图。',
    mark: '稿',
    hue: 6,
    agentKind: 'dashboard',
    singleton: false,
    moduleIds: ['wxdraft'],
    viewId: 'wxdraft',
    defaultAgentId: 'wxdraft',
    workspaceName: '公众号',
    group: '内容',
    suggestedCapabilities: ['secrets'],
  },
  {
    id: 'wxhub',
    role: '微信情报官',
    description: '本机只读微信情报：今日行动、待回复、商机分流和回复草稿。聊天不出本机，不发微信。',
    persona: '只在这台电脑上读微信情报库，把今日该处理的事和待分流候选写进收件箱。不发消息，不上传聊天。',
    mark: '微',
    hue: 5,
    agentKind: 'dashboard',
    singleton: true,
    moduleIds: ['wxhub'],
    viewId: 'wxhub',
    defaultAgentId: 'wxhub',
    workspaceName: '微信情报',
    group: '项目',
    suggestedCapabilities: ['todos:write', 'notify', 'subprocess'],
  },
  {
    id: 'mail',
    role: '邮件整理',
    description: '对接本机邮箱和 iCloud、Gmail、QQ，把收件箱收成待跟进、可归档和回信草稿。不代发邮件。',
    persona: '整理本机邮件.app 和 iCloud / Gmail / QQ 收件箱。只读、分流、写回信草稿，不代发。',
    mark: '邮',
    hue: 3,
    agentKind: 'dashboard',
    singleton: true,
    moduleIds: ['mail'],
    viewId: 'mail',
    defaultAgentId: 'mail',
    workspaceName: '邮件',
    group: '项目',
    suggestedCapabilities: ['secrets', 'subprocess'],
  },
  {
    id: 'notes',
    role: '随手记',
    description: '想到什么先记下来，不打断手里的事。',
    persona: '听到、想到就记，不打断你正在做的事。',
    mark: '记',
    hue: 0,
    agentKind: 'conversational',
    singleton: true,
    moduleIds: ['notes'],
    viewId: 'notes',
    defaultAgentId: 'notes',
    workspaceName: '随手记',
    group: '核心',
    suggestedCapabilities: ['search'],
  },
  {
    id: 'social-ammo',
    role: '社媒弹药手',
    description: '按最新产品能力生成六平台文案草稿，记录发布与互动数据。',
    persona: '按产品能力写出六平台文案，记下发布和互动。',
    mark: '弹',
    hue: 7,
    agentKind: 'dashboard',
    singleton: true,
    moduleIds: ['social-ammo'],
    viewId: 'social-ammo',
    defaultAgentId: 'social-ammo',
    workspaceName: '弹药',
    group: '内容',
    suggestedCapabilities: ['todos:write'],
  },
  {
    id: 'accounts',
    role: '自媒体账号',
    description: '管视频号、抖音、小红书上的多个账号，按日记录内容、数据与选材关联。',
    persona: '把各平台账号、日记和选材放在一起看。',
    mark: '号',
    hue: 2,
    agentKind: 'dashboard',
    singleton: true,
    moduleIds: ['accounts'],
    viewId: 'accounts',
    defaultAgentId: 'accounts',
    workspaceName: '账号',
    group: '内容',
    suggestedCapabilities: ['search'],
  },
  {
    id: 'pet',
    role: '台伴',
    description: '桌面角落的小鹿，待办到点会跳到屏幕中间提醒。',
    persona: '待办到点会跳到屏幕中间提醒你。',
    mark: '鹿',
    hue: 1,
    agentKind: 'window',
    singleton: true,
    moduleIds: ['pet'],
    defaultAgentId: 'pet',
    workspaceName: '台伴',
    group: '核心',
    suggestedCapabilities: ['window', 'notify'],
    inRoster: false,
  },
  {
    id: 'harness',
    role: 'DeepSeek 工作台',
    description: '官方 Agent 运行时。中栏对话和 Local API 共用同一棵 SDK 树，不再单独开官方 UI。',
    persona: '底层是 DeepSeek Harness。日常对话在中栏完成，不再单独嵌一套官方页面。',
    mark: 'H',
    hue: 3,
    agentKind: 'window',
    singleton: true,
    moduleIds: ['harness'],
    defaultAgentId: 'harness',
    workspaceName: 'Harness',
    group: '实验',
    suggestedCapabilities: [],
    inRoster: false,
  },
  {
    id: 'x-push',
    role: 'X 推送通道',
    description: '通过浏览器插件把草稿 DM 给自己或发成推文，本地桥监听 127.0.0.1:18753。',
    persona: '本地桥，把弹药送到 X。作为扩展能力挂在别的成员上。',
    mark: 'X',
    hue: 4,
    agentKind: 'background',
    singleton: true,
    moduleIds: ['x-push'],
    defaultAgentId: 'x-push',
    workspaceName: 'X',
    group: '内容',
    suggestedCapabilities: ['net:listen:18753'],
  },
]

const TEMPLATE_BY_ID = new Map(BUILTIN_TEMPLATES.map((template) => [template.id, template]))

export function templateById(id: string): AgentTemplate | undefined {
  return TEMPLATE_BY_ID.get(id)
}

/** 模块 id → 用于幂等创建默认实例的模板（组合模板不参与）。 */
export function templateForModule(moduleId: string): AgentTemplate | undefined {
  return BUILTIN_TEMPLATES.find(
    (template) => template.defaultAgentId !== '' && template.moduleIds.length === 1 && template.moduleIds[0] === moduleId,
  )
}

export function listedTemplates(): AgentTemplate[] {
  return BUILTIN_TEMPLATES.filter(
    (template) =>
      template.agentKind !== 'background' && template.inRoster !== false && template.inCatalog !== false,
  )
}
